apiVersion: v1
kind: Pod
metadata:
  name: "nvidia-test"
spec:
  restartPolicy: "OnFailure"
  nodeSelector:
    beta.kubernetes.io/instance-type: "p2.xlarge"
  tolerations:
  - key: "nvidia.com/gpu"
    effect: "NoSchedule"
  containers:
    - name: "cuda-vector-add"
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1
