# Default values for benchmarking.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: "vanvalenlab/kiosk-benchmarking"
  tag: "latest"
  pullPolicy: "Always"

resources: {}

env:
  NUM_CYCLES: 1
  NUM_GPUS: 1
  GRAFANA_USER: admin
  GRAFANA_PASSWORD: admin
  GRAFANA_HOST: grafana
  LOG_LEVEL: DEBUG
  API_HOST: '{{ env "CLUSTER_ADDRESS" | default "frontend" }}'
  FILE: specify_me
  COUNT: 1
  MODEL: dummy_model:dummy_version
  UPLOAD_PREFIX: uploads
  POSTPROCESS: ""
  PREPROCESS: ""
  START_DELAY: 1
  UPDATE_INTERVAL: 15
  MANAGER_REFRESH_RATE: 15
  EXPIRE_TIME: 3600
  CONCURRENT_REQUESTS_PER_HOST: 1
  STORAGE_BUCKET: specify_me
