sudo: true
dist: xenial

git:
  depth: false

language: bash

jobs:
  allow_failures:
    - script: make test/gke/deploy/elk
  fast_finish: true
  include:
    - stage: test
      name: "Integration test - no ELK"
      if: (branch = master) OR (commit_message =~ /[build-integration-tests]/)
      before_install:
        - openssl aes-256-cbc -K $encrypted_84460f9bb44c_key -iv $encrypted_84460f9bb44c_iv -in .travis/gcloud_key_base64.enc -out gcloud_key_base64 -d
        - cat gcloud_key_base64 | base64 --decode > gcloud_key.json
        - export PATH=/home/travis/build/vanvalenlab/kiosk:$PATH
      install: ./.travis/install_script.sh
      script: make test/gke/deploy
    - stage: test
      name: "Integration test - with ELK"
      if: (type = pull_request AND branch = master) OR (commit_message =~ /[build-integration-tests]/)
      before_install:
        - openssl aes-256-cbc -K $encrypted_84460f9bb44c_key -iv $encrypted_84460f9bb44c_iv -in .travis/gcloud_key_base64.enc -out gcloud_key_base64 -d
        - cat gcloud_key_base64 | base64 --decode > gcloud_key.json
        - export PATH=/home/travis/build/vanvalenlab/kiosk:/home/travis/build/vanvalenlab/kiosk/linux-amd64:$PATH
      install: ./.travis/install_script.sh
      script: make test/gke/deploy/elk
    - stage: deploy
      if: tag IS present
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$TRAVIS_REPO_SLUG" .
      - docker images
      - docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":latest
      - docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":"${TRAVIS_TAG}"
      - docker push "$TRAVIS_REPO_SLUG"
