# Default values for data-processing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: "vanvalenlab/kiosk-data-processing"
  tag: "latest"
  pullPolicy: "Always"

resources: {}

service:
  type: "ClusterIP"

  httpIngressEnabled: true
  internalHttpPort: 8080
  httpTargetPort: 8080
  externalHttpPort: 8080

  httpsIngressEnabled: false
  internalHttpsPort: 8443
  httpsTargetPort: 8443
  externalHttpsPort: 8443

  prometheusEnabled: true
  prometheusHttpPort: 8000

env:
  WORKERS: 10
  LISTEN_PORT: 8080
  PROMETHEUS_PORT: 8000
  PROMETHEUS_ENABLED: true
