# Default values for data-processing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: "vanvalenlab/kiosk-data-processing"
  tag: "0.1"
  pullPolicy: "Always"

deployment_port: 8080
container_name: "data-processing-container"
resources:
  # requests:
  #   cpu: 100m
  #   memory: 512Mi
  # limits:
  #   cpu: 100m
  #   memory: 512Mi
env:
  LISTEN_PORT: 8080

# service.yaml
service_name: "data-processing-service"
service_port: 8080
service_type: "ClusterIP"
