apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.app_name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service_account_name }}
  namespace: {{ .Release.Namespace }}
