apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: {{ .Values.container_name }}
        image: {{ .Values.image_name }}:{{ .Values.image_version }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.deployment_port }}
        env:
        - name: PORT
          value: {{ .Values.deployment_port | quote }}
        - name: REDIS_HOST
          value: {{ .Values.env.REDIS_HOST }}
        - name: REDIS_PORT
          value: {{ .Values.env.REDIS_PORT | quote }}
{{- range $name, $value := .Values.env.secret }}
{{- if not ( empty $value) }}
        - name: {{ $name }}
          valueFrom:
            secretKeyRef:
              name: fe-rd-env-variables
              key: {{ $name | lower }}
{{- end }}
{{- end }}

