apiVersion: v1
kind: Secret
metadata:
  name: redis-consumer-env-variables
type: Opaque
data:
{{- range $name, $value := .Values.secrets }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
