app_name: "redis-consumer"

# deployment.yaml
deployment_name: "redis-consumer-deployment"
replicas: 1
image_name: "vanvalenlab/kiosk-redis-consumer"
image_tag: "latest"
deployment_port: 8080
container_name: "redis-consumer-container"
env:
  REDIS_HOST: "redis-master-0"
  REDIS_PORT: "6379"
  TF_HOST: "overwrite_this"
  TF_PORT: "sepcify_me"
  AWS_REGION: "us-east-1"
  DEBUG: "True"
  CLOUD_PROVIDER: "aws"
  GKE_COMPUTE_ZONE: "us-west1-b"

# service.yaml
service_name: "redis-consumer-service"
service_port: 8080
service_type: "ClusterIP"

# secrets.yaml
secrets:
  AWS_ACCESS_KEY_ID: "change_me"
  AWS_SECRET_ACCESS_KEY: "change_me"
  AWS_S3_BUCKET: "change_me"
  GKE_BUCKET: "change_me"
