# Default values for redis-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: "vanvalenlab/kiosk-redis-consumer"
  tag: "drift"
  pullPolicy: "Always"

resources: {}

service:
  type: "ClusterIP"

  httpIngressEnabled: true
  internalHttpPort: 8080
  httpTargetPort: 8080
  externalHttpPort: 8080

  httpsIngressEnabled: false

env:
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  TF_HOST: "overwrite_this"
  TF_PORT: "sepcify_me"
  AWS_REGION: "us-east-1"
  DEBUG: "True"
  CLOUD_PROVIDER: "aws"
  GKE_COMPUTE_ZONE: "us-west1-b"
  LABEL_DETECT_ENABLED: true
  SCALE_DETECT_ENABLED: true
  TRACKING_MODEL: tracking_model_benchmarking_757_step5_20epoch_80split_9tl:1
  NUCLEAR_POSTPROCESS: retinanet-semantic
  PHASE_MODEL: resnet50_retinanet_20190813_all_phase_512:0
  PHASE_POSTPROCESS: retinanet
  CYTOPLASM_MODEL: resnet50_retinanet_20190903_all_fluorescent_cyto_512:0
  CYTOPLASM_POSTPROCESS: retinanet-semantic

secrets:
  AWS_ACCESS_KEY_ID: "change_me"
  AWS_SECRET_ACCESS_KEY: "change_me"
  AWS_S3_BUCKET: "change_me"
  GKE_BUCKET: "change_me"
