---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tf-serving
  namespace: deepcell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tf-serving
  minReplicas: 1
  maxReplicas: $GPU_NODE_MAX_SIZE
  metrics:
  - type: Object
    object:
      metricName: tf_serving_scale_metric
      target:
        apiVersion: v1
        kind: Namespace
        name: tf_serving_scale_metric
      targetValue: 70
---
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: data-processing
#   namespace: deepcell
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: data-processing
#   minReplicas: 1
#   maxReplicas: $GPU_MAX_TIMES_TWENTY
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 80
# ---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: deepcell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: $GPU_MAX_TIMES_TEN
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-consumer
  namespace: deepcell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-consumer
  minReplicas: 1
  maxReplicas: $GPU_MAX_TIMES_ONE_HUNDRED
  metrics:
  - type: Object
    object:
      metricName: redis_consumer_key_ratio
      target:
        apiVersion: v1
        kind: Namespace
        name: redis_consumer_key_ratio
      targetValue: .15
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zip-consumer
  namespace: deepcell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zip-consumer
  minReplicas: 1
  maxReplicas: $GPU_MAX_TIMES_ONE_HUNDRED
  metrics:
  - type: Object
    object:
      metricName: zip_consumer_key_ratio
      target:
        apiVersion: v1
        kind: Namespace
        name: zip_consumer_key_ratio
      targetValue: 1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tracking-consumer
  namespace: deepcell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tracking-consumer
  minReplicas: 1
  maxReplicas: $GPU_MAX_TIMES_FIFTY
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
