apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
    spec:
      # TODO: generalize the node selectors
      nodeSelector:
        rc_dp: "yes"
      tolerations:
      - key: rc_dp
        operator: Exists
        effect: NoSchedule
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.internalHttpPort }}
            protocol: TCP
          - name: https
            containerPort: {{ .Values.service.internalHttpsPort }}
            protocol: TCP
          - name: prometheus
            containerPort: {{ .Values.service.prometheusHttpPort }}
            protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
{{- range $name, $value := .Values.env }}
{{- if not ( empty $value) }}
        - name: {{ $name }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
{{ $secrets_name := .Values.secrets_name }}
{{- range $name, $value := .Values.secrets }}
{{- if not ( empty $value) }}
        - name: {{ $name }}
          valueFrom:
            secretKeyRef:
              name: {{ $secrets_name }}
              key: {{ $name }}
{{- end }}
{{- end }}
