kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.prometheusEnabled }}
  - name: prometheus
    targetPort: {{ .Values.service.prometheusHttpPort }}
    port: {{ .Values.service.prometheusHttpPort }}
    protocol: TCP
  {{- end }}
  {{- if .Values.service.httpIngressEnabled }}
  - name: http
    targetPort: {{ .Values.service.httpTargetPort }}
    port: {{ .Values.service.externalHttpPort }}
    protocol: TCP
  {{- end }}
  {{- if .Values.service.httpsIngressEnabled }}
  - name: https
    targetPort: {{ .Values.service.httpsTargetPort }}
    port: {{ .Values.service.externalHttpsPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ template "fullname" . }}
