app_name: "frontend"

#deployment.yaml
replicas: 1
image_name: "vanvalenlab/react_interface"
image_version: "latest"
deployment_name: "frontend-deployment"
deployment_port: 3000
container_name: "frontend-container"

# service.yaml
service_name: "frontend-service"
service_port: 3000
service_type: "ClusterIP"

# ingress.yaml
ingress_name: "frontend-ingress"
ingress_path: "/"

# secrets.yaml and hemlfile.d/frontend.yaml
env:
  PORT: "8080"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  MODEL_PREFIX: "models/"
  AWS_REGION: "us-east-1"
  CLOUD_PROVIDER: "aws"
secrets:
  AWS_ACCESS_KEY_ID: "change_me"
  AWS_SECRET_ACCESS_KEY: "change_me"
  AWS_S3_BUCKET: "change_me"
  GCLOUD_STORAGE_BUCKET: "change_me"
  GCLOUD_PROJECT_ID: "change_me"
  GCLOUD_KEY_FILE: "change_me"
