app_name: "frontend"

#deployment.yaml
replicas: 1
image_name: "vanvalenlab/kiosk-frontend"
image_version: "latest"
#image_name: "k8s.gcr.io/echoserver"
#image_version: "1.4"
deployment_name: "frontend-deployment"
deployment_port: 3001
container_name: "frontend-container"

# service.yaml
service_name: "frontend-service"
service_port: 3000
service_type: "ClusterIP"

# ingress.yaml
ingress_name: "frontend-ingress"
ingress_path: "/"
ingress:
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/proxy-body-size: "25m"

# secrets.yaml and hemlfile.d/frontend.yaml
env:
  PORT: "8080"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  MODEL_PREFIX: "models/"
  AWS_REGION: "us-east-1"
  CLOUD_PROVIDER: "aws"
secrets:
  AWS_ACCESS_KEY_ID: "change_me"
  AWS_SECRET_ACCESS_KEY: "change_me"
  AWS_S3_BUCKET: "change_me"
  GCLOUD_STORAGE_BUCKET: "change_me"
  GCLOUD_PROJECT_ID: "change_me"
