apiVersion: v1
name: flask-middleman
version: 0.1.0
kubeVersion: ^1.9.8
description: This project provides the interface between the frontend and the Tensorflow-serving backend.
keywords:
  - flask
home: https://www.github.com/vanvalenlab/model_server
sources:
  - https://hub.docker.com/vanvalenlab/model_server
maintainers:
  - name: Dylan Bannon
    email: bbannon@caltech.edu
    url: vanvalen.caltech.edu
engine: gotpl
appVersion: 0.1.0
deprecated: false
tillerVersion: ^2.9.1

