repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:

################################################################################
## ElasticSearch ###############################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/elasticsearch
#
- name: elasticsearch
  namespace: elk
  labels:
    chart: elasticsearch
    component: elasticsearch
    namespace: elk
    vendor: elastic.co
    default: true
  chart: stable/elasticsearch
  version: 1.32.5
  wait: true
  timeout: 600
  atomic: true
  cleanupOnFail: true
  values:
    - client:
        heapSize: 512m
        # additionalJavaOpts: "-XX:MaxRAM=512m"
        resources:
          limits:
            cpu: 1
            # memory: 1024Mi
          requests:
            cpu: 25m
            memory: 768Mi

      master:
        replicas: 3
        heapSize: 512m
        # additionalJavaOpts: "-XX:MaxRAM=512m"
        resources:
          limits:
            cpu: 1
            # memory: 1024Mi
          requests:
            cpu: 25m
            memory: 768Mi

      data:
        heapSize: 1536m
        # additionalJavaOpts: "-XX:MaxRAM=1536m"
        nodeSelector:
          elasticsearch_data: "yes"
        tolerations:
        - key: elasticsearch_data
          operator: Exists
          effect: NoSchedule
        resources:
          limits:
            ### Resource limits removed because elasticsearch-data-* pods are being scheduled to their own nodes now
            # cpu: 1
            # memory: 2048Mi
          requests:
            cpu: 300m
            # memory: 10Gi
