repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:

################################################################################
## Kibana ######################################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/kibana
#
- name: kibana
  namespace: elk
  labels:
    chart: kibana
    component: kibana
    namespace: elk
    vendor: elastic.co
    default: true
  chart: stable/kibana
  version: 3.2.8
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  values:
    - resources:
        requests:
          memory: 128Mi

      files:
        kibana.yml:
          server.name: kibana
          server.host: 0
          elasticsearch.url: http://elasticsearch-client:9200

      service:
        type: ClusterIP
        externalPort: 443
        internalPort: 5601

      ingress:
        enabled: true
        hosts:
          - dev.logging.deepcell.org
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/proxy-body-size: "1g"
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
