repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:

################################################################################
## FileBeat ####################################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/filebeat
#
- name: filebeat
  namespace: elk
  labels:
    chart: filebeat
    component: filebeat
    namespace: elk
    vendor: elastic.co
    default: true
  chart: stable/filebeat
  version: 4.0.2
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  values:
    - config:
        output.logstash:
          enabled: true
          hosts: ["logstash:5044"]
          username: elastic
          password: changeme

      tolerations:
        - operator: Exists
          effect: NoSchedule
