apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: "Always"
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.service.internalHttpPort }}
            protocol: TCP
          - name: grpc
            containerPort: {{ .Values.service.internalGrpcPort }}
            protocol: TCP
        env:
{{- range $name, $value := .Values.env }}
{{- if not ( empty $value) }}
        - name: {{ $name }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
{{ $dot := . }}
{{- range $name, $value := .Values.secrets }}
{{- if not ( empty $value) }}
        - name: {{ $name }}
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" $dot }}
              key: {{ $name }}
{{- end }}
{{- end }}
