apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "chart" . }}
    app: {{ template "name" . }}
  annotations:
{{- range $name, $value := .Values.service.annotations }}
{{- if not ( empty $value) }}
    {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.grpcIngressEnabled }}
  - name: grpc
    targetPort: {{ .Values.service.grpcTargetPort }}
    port: {{ .Values.service.externalGrpcPort }}
    protocol: TCP
  {{- end }}
  {{- if .Values.service.httpIngressEnabled }}
  - name: http
    targetPort: {{ .Values.service.httpTargetPort }}
    port: {{ .Values.service.externalHttpPort }}
    protocol: TCP
  {{- end }}
  {{- if .Values.service.httpsIngressEnabled }}
  - name: https
    targetPort: {{ .Values.service.httpsTargetPort }}
    port: {{ .Values.service.externalHttpsPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ template "fullname" . }}
