# Default values for bucket-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: vanvalenlab/kiosk-bucket-monitor
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

env:
  LOG_LEVEL: "DEBUG"
  INTERVAL: "21600"
  AGE_THRESHOLD: "604800"
  PREFIX: "uploads/,output/"
  STORAGE_BUCKET: "s3://default-bucket"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
