# Default values for bucket-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: "vanvalenlab/kiosk-bucket-monitor"
  tag: "latest"
  pullPolicy: "Always"

resources: {}

env:
  DEBUG: "true"
  INTERVAL: 10
  CLOUD_PROVIDER: "overwrite_this"
  BUCKET: "overwrite_this"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
