app_name: "elasticsearch"

# deployment.yaml
deployment_name: "elasticsearch-deployment"
replicas: 1
image_name: "vanvalenlab/kiosk-elasticsearch"
image_tag: "latest"
deployment_port: 6006
container_name: "elasticsearch-container"
env:
  LOG_PREFIX: "elasticsearch_logs"
  CLOUD_PROVIDER: "aws"
  GKE_COMPUTE_ZONE: "us-west1-b"

# service.yaml
service_name: "elasticsearch-service"
service_port: 6006
service_type: "ClusterIP"

# ingress.yaml
ingress_name: "elasticsearch-ingress"
ingress_path: "/elasticsearch"
ingress:
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/proxy-body-size: "25m"

# secrets.yaml
secrets_name: "elasticsearch-env-variables"
secrets:
  AWS_ACCESS_KEY_ID: "change_me"
  AWS_SECRET_ACCESS_KEY: "change_me"
  AWS_S3_BUCKET: "change_me"
  GKE_BUCKET: "change_me"
