helmDefaults:
  wait: true
  timeout: 600
  force: true

################################################################################
## Certificate Manager #########################################################
################################################################################

repositories:
  # Add the Jetstack Helm repository
  - name: jetstack
    url: https://charts.jetstack.io

releases:

#
# References:
#   - https://github.com/cloudposse/charts/blob/master/incubator/nginx-ingress/values.yaml
#
- name: cert-manager
  namespace: cert-manager
  labels:
    chart: cert-manager
    repo: jetstack
    component: cert-manager
    namespace: cert-manager
    vendor: kubernetes
  chart: jetstack/cert-manager
  version: 1.1.0
  wait: true
  atomic: true
  cleanupOnFail: true
  hooks:
  - events: ["postsync"]
    # Give cert-manager time to initialize itself
    showlogs: true
    command: /bin/sleep
    args:
      - 15
  values:
    - installCRDs: true

      # serviceAccount:
      #   annotations:
      #     iam.gke.io/gcp-service-account: {{ env "GCP_CLOUD_DNS_SERVICE_ACCOUNT" | default "cloud-dns-sa-not-found"}}

      ingressShim:
        # Use "letsencrypt-prod" for production.
        defaultIssuerName: {{ env "CERTIFICATE_MANAGER_CLUSTER_ISSUER" | default "letsecrypt-staging" }}
        defaultIssuerKind: ClusterIssuer
        defaultIssuerGroup: cert-manager.io
