helmDefaults:
  wait: true
  timeout: 600
  force: true

################################################################################
## Redis Data Store ############################################################
################################################################################

repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  # Redis
  - name: redis
    labels:
      chart: redis
      component: database
    chart: stable/redis
    version: 10.5.7
    namespace: deepcell
    values:
      - resources:
          requests:
            cpu: 200m
            memory: 256Mi

        usePassword: false

        cluster:
          enabled: true
          slaveCount: 2

        sentinel:
          enabled: true

        configmap: |-
          # Enable AOF https://redis.io/topics/persistence#append-only-file
          appendonly yes
          # Disable RDB persistence, AOF persistence already enabled.
          save ""
          no-appendfsync-on-rewrite yes

        sysctlImage:
          enabled: true
          mountHostSys: true
          command:
            - /bin/sh
            - -c
            - |-
              install_packages systemd
              sysctl -w net.core.somaxconn=10000
              echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
