helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

################################################################################
## Redis Data Store ############################################################
################################################################################

repositories:
 # Stable repo of official helm charts
 - name: "stable"
   url: "https://kubernetes-charts.storage.googleapis.com"
releases:
 # Redis
 - name: "redis"
   labels:
     chart: "redis"
     component: "database"
   chart: "stable/redis"
   version: "3.0.5"
   namespace: "deepcell"
   set:
     - name: "usePassword"
       value: "false"
     - name: "cluster.enabled"
       value: "false"
   values:
     - resources:
         requests:
           cpu: 200m
           memory: 256Mi
