helmDefaults:
  wait: true
  timeout: 600
  force: true

################################################################################
## Redis Monitoring ############################################################
################################################################################

repositories:
 # Stable repo of official helm charts
  - name: "stable"
    url: "https://kubernetes-charts.storage.googleapis.com"

releases:
  - name: "prometheus-redis-exporter"
    labels:
      chart: "prometheus-redis-exporter"
    chart: "stable/prometheus-redis-exporter"
    version: "3.2.1"
    namespace: "monitoring"
    component: "monitoring"
    values:
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi

        script:
          configmap: prometheus-redis-exporter-script
          keyname: script

        service:
          annotations:
            prometheus.io/path: /metrics
            prometheus.io/port: "9121"
            prometheus.io/scrape: "true"

        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "9121"
          prometheus.io/scrape: "true"

        redisAddress: redis://redis.deepcell:6379
