repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:

################################################################################
## Redis Monitoring ############################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/blob/master/stable/prometheus-redis-exporter/values.yaml
#
- name: prometheus-redis-exporter
  chart: stable/prometheus-redis-exporter
  namespace: monitoring
  labels:
    chart: prometheus-redis-exporter
    component: monitoring
    namespace: monitoring
  version: 3.5.0
  wait: true
  timeout: 120
  atomic: true
  cleanupOnFail: true
  values:
    - script:
        configmap: prometheus-redis-exporter-script
        keyname: script

      service:
        annotations:
          prometheus.io/path: "/metrics"
          prometheus.io/port: "9121"
          prometheus.io/scrape: "true"

      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9121"
        prometheus.io/scrape: "true"

      redisAddress: redis://redis.deepcell:6379
