helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Bucket-Monitor ##############################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "bucket-monitor"
  namespace: "deepcell"
  labels:
    chart: "bucket-monitor"
    component: "bucket-monitor"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/bucket-monitor'
  version: "0.1.0"
  values:
    - replicas: 0

      image:
        repository: "vanvalenlab/kiosk-bucket-monitor"
        tag: "redis-cluster"
        pullPolicy: "Always"

      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi

      env:
        DEBUG: "true"
        INTERVAL: "5"
        REDIS_HOST: "redis"
        REDIS_PORT: "26379"
        CLOUD_PROVIDER: {{ env "CLOUD_PROVIDER" | default "broken_default" }}
{{ if eq (env "CLOUD_PROVIDER" | default "aws") "aws" }}
        BUCKET: {{ env "BUCKET" | default "broken_default" }}
{{ else }}
        BUCKET: {{ env "GKE_BUCKET" | default "broken_default" }}
{{ end }}
