helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## AutoScaler ################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "as"
  namespace: "deepcell"
  labels:
    chart: "autoscaler"
    component: "autoscaler"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/autoscaler'
  version: "0.1.0"
  values:
    - app_name: "autoscaler"
      deployment_name: "autoscaler-deployment"
      replicas: 1
      image_name: "vanvalenlab/kiosk-autoscaler"
      image_version: "zip"
      container_name: "autoscaler-container"
      service_account_name: "autoscaler-service-account"
      env:
        DEBUG: "true"
        INTERVAL: "5"
        REDIS_HOST: "redis-master"
        REDIS_PORT: "6379"
        AUTOSCALING: "0|1|5|deepcell|deployment|predict|tf-serving-deployment; 0|1|5|deepcell|deployment|predict|redis-consumer-deployment; 0|5|1|deepcell|deployment|predict|zip-consumer-deployment; 0|4|1|deepcell|job|train|training-job"
