helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Kibana ######################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "ki"
  namespace: "deepcell"
  labels:
    chart: "kibana"
    component: "kibana"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/kibana'
  version: "0.1.0"
  values:
    - image:
        repository: "docker.elastic.co/kibana/kibana-oss"
        tag: "6.6.0"
        pullPolicy: "IfNotPresent"
      commandline:
        args: []
      env: {}
      files:
        kibana.yml:
          server.name: kibana
          server.host: "ki-kibana"
          elasticsearch.url: es-elasticsearch-client:9200
      deployment:
        annotations: {}
      service:
        type: ClusterIP
        externalPort: 443
        internalPort: 5601
        annotations: {}
        labels: {}
      ingress:
        enabled: true
        host:
          - " /kibana" # leading space necessary
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: 1g
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
      serviceAccount:
        create: false
        name:
      livenessProbe:
        enabled: false
        initialDelaySeconds: 30
        timeoutSeconds: 10
      readinessProbe:
        enabled: false
        initialDelaySeconds: 30
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 5
      authProxyEnabled: false
      extraContainers: |
      extraVolumeMounts: []
      extraVolumes: []
      resources: {}
      priorityClassName: ""
      tolerations: []
      nodeSelector: {}
      podAnnotations: {}
      replicaCount: 1
      revisionHistoryLimit: 3
      dashboardImport:
        timeout: 60
        xpackauth:
          enabled: false
          username: myuser
          password: mypass
        dashboards: {}
      plugins:
        enabled: false
        reset: false
        values:
      persistentVolumeClaim:
        enabled: false
        existingClaim: false
        annotations: {}
        accessModes:
          - ReadWriteOnce
        size: "5Gi"
      securityContext:
        enabled: false
        allowPrivilegeEscalation: false
        runAsUser: 1000
        fsGroup: 2000
      extraConfigMapMounts: []
