helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## AutoScaler ################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "autoscaler"
  namespace: "deepcell"
  labels:
    chart: "autoscaler"
    component: "autoscaler"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/autoscaler'
  version: "0.1.0"
  values:
    - app_name: "autoscaler"
      deployment_name: "autoscaler-deployment"
      replicas: 1
      image_name: "vanvalenlab/kiosk-autoscaler"
      image_version: "tracking-0.1"
      container_name: "autoscaler-container"
      service_account_name: "autoscaler-service-account"
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi
# 1|{{ env "GPU_NODE_MAX_SIZE" | default 10 }}|1|deepcell|deployment|predict|zip-consumer-deployment;
      env:
        DEBUG: "true"
        INTERVAL: "5"
        REDIS_HOST: "redis-master"
        REDIS_PORT: "6379"
{{ if eq (env "CLOUD_PROVIDER" | default "aws") "aws" }}
        AUTOSCALING: >
            {{ env "AWS_MIN_GPU_NODES" | default 0 }}|{{ env "AWS_MAX_GPU_NODES" | default 5 }}|1|deepcell|deployment|predict|tf-serving-deployment;
            {{ env "AWS_MIN_GPU_NODES" | default 0 }}|{{ env "AWS_MAX_GPU_NODES" | default 5 }}|1|deepcell|deployment|track|tf-serving-deployment;
            0|4|1|deepcell|job|train|training-job
        SECONDARY_AUTOSCALING: >
            redis-consumer-deployment|deployment|deepcell|tf-serving-deployment|deployment|deepcell|7|0|{{ env "GPU_MAX_TIMES_FIFTY" | default 0 }};
            tracking-consumer-deployment|deployment|deepcell|tf-serving-deployment|deployment|deepcell|7|0|{{ env "GPU_MAX_TIMES_FIFTY" | default 0 }};
            data-processing-deployment|deployment|deepcell|tf-serving-deployment|deployment|deepcell|1|0|{{ env "GPU_MAX_TIMES_TEN" | default 0 }}
{{ else }}
        AUTOSCALING: >
            {{ env "GPU_NODE_MIN_SIZE" | default 0 }}|{{ env "GPU_NODE_MAX_SIZE" | default 5 }}|1|deepcell|deployment|predict|tf-serving-deployment;
            {{ env "GPU_NODE_MIN_SIZE" | default 0 }}|{{ env "GPU_NODE_MAX_SIZE" | default 5 }}|1|deepcell|deployment|track|tf-serving-deployment;
            0|4|1|deepcell|job|train|training-job
        SECONDARY_AUTOSCALING: >
            redis-consumer-deployment|deployment|deepcell|tf-serving-deployment|deployment|deepcell|12|0|{{ env "GPU_MAX_TIMES_FIFTY" | default 0 }};
            tracking-consumer-deployment|deployment|deepcell|tf-serving-deployment|deployment|deepcell|12|0|{{ env "GPU_MAX_TIMES_FIFTY" | default 0 }};
            data-processing-deployment|deployment|deepcell|tf-serving-deployment|deployment|deepcell|1|0|{{ env "GPU_MAX_TIMES_TEN" | default 0 }}
{{ end }}
