helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## AutoScaler ################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "bm"
  namespace: "deepcell"
  labels:
    chart: "benchmarking"
    component: "benchmarking"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/benchmarking'
  version: "0.1.0"
  values:
    - app_name: "benchmarking"
      deployment_name: "benchmarking-deployment"
      replicas: 1
      image_name: "vanvalenlab/kiosk-benchmarking"
      image_version: "multiple_zip_files"
      container_name: "benchmarking-container"
      service_account_name: "benchmarking-service-account"
      env:
        BENCHMARKING_PU_TYPE_AND_NUMBER: '{{ env "BENCHMARKING_PU_TYPE_AND_NUMBER" | default "NA" }}'
        BENCHMARKING_PU_TYPE: '{{ env "BENCHMARKING_PU_TYPE" | default "NA" }}'
        IMG_NUM: '{{ env "IMG_NUM" | default "0" }}'
        BENCHMARK_MODEL: '{{ env "BENCHMARK_MODEL" | default "NA" }}'
        BENCHMARK_MODEL_VERSION: '{{ env "BENCHMARK_MODEL_VERSION" | default "NA" }}'
        BENCHMARK_POSTPROCESSING: '{{ env "BENCHMARK_POSTPROCESSING" | default "NA" }}'
        BENCHMARK_CUTS: '{{ env "BENCHMARK_CUTS" | default "NA" }}'
        GPU_TYPE: '{{ env "GPU_TYPE" | default "NA" }}'
        CLUSTER_ADDRESS: '{{ env "CLUSTER_ADDRESS" | default "NA" }}'
