helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Tracking-Consumer ################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "tracking-consumer"
  namespace: "deepcell"
  labels:
    chart: "redis-consumer"
    component: "deepcell"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/redis-consumer'
  version: "0.1.0"
  values:
    - replicas: 1

      image:
        repository: "vanvalenlab/kiosk-redis-consumer"
        tag: "dev"
        pullPolicy: "Always"

      nameOverride: "tracking-consumer"

      resources:
        requests:
          cpu: 300m
          memory: 256Mi
        # limits:
        #   cpu: 100m
        #   memory: 1024Mi

      env:
        REDIS_HOST: "redis"
        REDIS_PORT: "26379"
        TF_HOST: "tf-serving"
        TF_PORT: "8500"
        DEBUG: "True"
        AWS_REGION: '{{ env "AWS_REGION" | default "us-east-1" }}'
        CLOUD_PROVIDER: '{{ env "CLOUD_PROVIDER" | default "aws" }}'
        GKE_COMPUTE_ZONE: '{{ env "GKE_COMPUTE_ZONE" | default "us-west1-b" }}'
        CONSUMER_TYPE: "tracking"
        QUEUE: "track"
        LABEL_DETECT_ENABLED: True
        SCALE_DETECT_ENABLED: True
        NUCLEAR_POSTPROCESS: retinanet-semantic
        DRIFT_CORRECT_ENABLED: False

      secrets:
        AWS_ACCESS_KEY_ID: '{{ env "AWS_ACCESS_KEY_ID" | default "NA" }}'
        AWS_SECRET_ACCESS_KEY: '{{ env "AWS_SECRET_ACCESS_KEY" | default "NA" }}'
        AWS_S3_BUCKET: '{{ env "AWS_S3_BUCKET" | default "NA" }}'
        GKE_BUCKET: '{{ env "GKE_BUCKET" | default "NA" }}'
