helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Frontend ####################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "fe"
  namespace: "deepcell"
  labels:
    chart: "frontend"
    component: "deepcell"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/frontend'
  version: "0.1.0"
  values:
    - app_name: "frontend"
      replicas: 1
      image_name: "vanvalenlab/react_interface"
      image_version: "0.1dev"
      deployment_name: "frontend-deployment"
      deployment_port: 3000
      container_name: "frontend-container"
      service_name: "frontend-service"
      service_port: 3000
      service_type: "ClusterIP"
      ingress_name: "frontend-ingress"
      ingress_path: "/" 
      env:
        PORT: "8080"
        REDIS_HOST: "redis-master"
        REDIS_PORT: "6379"
        MODEL_PREFIX: "models/"
        AWS_REGION: "us-east-1"
        CLOUD_PROVIDER: '{{ env "CLOUD_PROVIDER" | default "gce" }}'
      secrets:
        AWS_ACCESS_KEY_ID: '{{ env "AWS_ACCESS_KEY_ID" | default "NA" }}'
        AWS_SECRET_ACCESS_KEY: '{{ env "AWS_SECRET_ACCESS_KEY" | default "NA" }}'
        AWS_S3_BUCKET: '{{ env "AWS_S3_BUCKET" | default "NA" }}'
        GCLOUD_STORAGE_BUCKET: '{{ env "GCLOUD_STORAGE_BUCKET" | default "NA" }}'
        GCLOUD_PROJECT_ID: '{{ env "GCLOUD_PROJECT_ID" | default "NA" }}'
        GCLOUD_KEY_FILE: '{{ env "GCLOUD_KEY_FILE" | default "NA" }}'
