helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Tensorflow-Serving ##########################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "tf-serving"
  namespace: "deepcell"
  labels:
    chart: "tf-serving"
    component: "deepcell"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/tf-serving'
  version: "0.1.0"
  values:
    - app_name: "tf-serving"
      replicas: 0
      resources:
        requests:
          nvidia.com/gpu: 1
          cpu: 100m
          memory: 1024Mi
        limits:
          nvidia.com/gpu: 1
        #   cpu: 100m
        #   memory: 2048Mi
      image_name: "vanvalenlab/kiosk-tf-serving"
      image_version: "0.1"
      deployment_name: "tf-serving-deployment"
      deployment_port: 8500
      container_name: "tf-serving-container"
      service_name: "tf-serving-service"
      service_port: 8500
      service_type: "ClusterIP"
      nodeSelector:
{{ if eq (env "CLOUD_PROVIDER" | default "aws") "aws" }}
        beta.kubernetes.io/instance-type: '{{ env "AWS_GPU_MACHINE_TYPE" | default "p2.xlarge" }}'
{{ else }}
        cloud.google.com/gke-accelerator: '{{ env "GPU_TYPE" | default "nvidia-tesla-k80" }}'
        cloud.google.com/gke-preemptible: "true"
{{ end }}
      env:
        PORT: "8500"
        REST_API_PORT: "0"
        REST_API_TIMEOUT: "30000"
        MODEL_CONFIG_FILE: "/kiosk/tf-serving/models.conf"
        ENABLE_BATCHING: "false"
        GRPC_CHANNEL_ARGS: ""
        MODEL_PREFIX: "models"
        CLOUD_PROVIDER: '{{ env "CLOUD_PROVIDER" | default "aws" }}'
        LOG_LEVEL: "3"
        DEBUG: "FALSE"
      secrets:
        AWS_ACCESS_KEY_ID: '{{ env "AWS_ACCESS_KEY_ID" | default "NA" }}'
        AWS_SECRET_ACCESS_KEY: '{{ env "AWS_SECRET_ACCESS_KEY" | default "NA" }}'
        AWS_S3_BUCKET: '{{ env "AWS_S3_BUCKET" | default "NA" }}'
        GCLOUD_STORAGE_BUCKET: '{{ env "GKE_BUCKET" | default "NA" }}'
