helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Tensorflow-Serving ##########################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "tf"
  namespace: "deepcell"
  labels:
    chart: "tf-serving"
    component: "deepcell"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/tf-serving'
  version: "0.1.0"
  values:
    - app_name: "tf-serving"
      replicas: 0
      image_name: "vanvalenlab/tf_serving_s3"
      image_version: "0.1dev"
      deployment_name: "tf-serving-deployment"
      deployment_port: 8501
      container_name: "tf-serving-container"
      service_name: "tf-serving-service"
      service_port: 1337
      service_type: "ClusterIP"
      env:
        RPC_PORT: "8500"
        REST_PORT: "8501"
        REST_TIMEOUT: "90000"
        MODEL_PREFIX: "models"
        LOG_LEVEL: "3"
      secrets:
        AWS_ACCESS_KEY_ID: '{{ env "AWS_ACCESS_KEY_ID" | default "NA" }}'
        AWS_SECRET_ACCESS_KEY: '{{ env "AWS_SECRET_ACCESS_KEY" | default "NA" }}'
        AWS_S3_BUCKET: '{{ env "AWS_S3_BUCKET" | default "NA" }}'
