helmDefaults:
  wait: true
  timeout: 600
  force: true

releases:

################################################################################
## TensorBoard #################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "tensorboard"
  namespace: "deepcell"
  labels:
    chart: "tensorboard"
    component: "deepcell"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/tensorboard'
  version: "0.1.0"
  values:
    - replicas: 0

      image:
        repository: "vanvalenlab/kiosk-tensorboard"
        tag: "0.1"

      service:
        type: "ClusterIP"

        httpIngressEnabled: "false"
        internalHttpPort: 6006
        httpTargetPort: 6006
        externalHttpPort: 6006

        httpsIngressEnabled: false

      ingress:
        enabled: "false"
        path: /tensorboard
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: "1g"
          kubernetes.io/ingress.class: "nginx"

      resources:
        requests:
          cpu: 100m
          memory: 128Mi

      env:
        LOG_PREFIX: "tensorboard_logs"
        CLOUD_PROVIDER: '{{ env "CLOUD_PROVIDER" | default "aws" }}'
        GKE_COMPUTE_ZONE: '{{ env "GKE_COMPUTE_ZONE" | default "us-west1-b" }}'

      secrets:
        AWS_ACCESS_KEY_ID: '{{ env "AWS_ACCESS_KEY_ID" | default "NA" }}'
        AWS_SECRET_ACCESS_KEY: '{{ env "AWS_SECRET_ACCESS_KEY" | default "NA" }}'
        AWS_S3_BUCKET: '{{ env "AWS_S3_BUCKET" | default "NA" }}'
        GKE_BUCKET: '{{ env "CLOUDSDK_BUCKET" | default "NA" }}'
