helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Kibana ######################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "metricbeat"
  namespace: "deepcell"
  labels:
    chart: "merticbeat"
    component: "metricbeat"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: "stable/metricbeat"
  version: "1.0.0"
  values:
    - image:
        repository: "docker.elastic.co/beats/metricbeat"
        tag: "6.6.0"
        pullPolicy: "Always"
      # The instances created by daemonset retrieve most metrics from the host
      daemonset:
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        config:
          output.logstash:
            enabled: true
            hosts: ["logstash:5044"]
            username: "elastic"
            password: "changeme"
          setup.kibana:
            host: "http://kibana:443"
          metricbeat.config:
            modules:
              path: ${path.config}/modules.d/*.yml
              reload.enabled: false
          processors:
          - add_cloud_metadata:
          output.file:
            enabled: false
