helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Kibana ######################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "fb"
  namespace: "deepcell"
  labels:
    chart: "filebeat"
    component: "filebeat"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: "stable/filebeat"
  version: "1.0.0"
  values:
    - image:
        repository: "docker.elastic.co/beats/filebeat"
        tag: "6.6.0"
        pullPolicy: "Always"
      config:
        filebeat.config:
          prospectors:
            # Mounted `filebeat-prospectors` configmap:
            path: ${path.config}/prospectors.d/*.yml
            # Reload prospectors configs as they change:
            reload.enabled: false
          modules:
            path: ${path.config}/modules.d/*.yml
            # Reload module configs as they change:
            reload.enabled: false
        processors:
          - add_cloud_metadata:
        filebeat.prospectors:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log
              - /var/log/messages
              - /var/log/syslog
          - type: docker
            containers.ids:
            - "*"
            processors:
              - add_kubernetes_metadata:
                  in_cluster: true
              - drop_event:
                  when:
                    equals:
                      kubernetes.container.name: "filebeat"
        output.file:
          enabled: false
          path: "/usr/share/filebeat/data"
          filename: filebeat
          rotate_every_kb: 10000
          number_of_files: 5
        output.elasticsearch:
          enabled: true
          hosts: ["http://es-elasticsearch-client:9200"]
          #index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
          username: "elastic"
          password: "changeme"
        # When a key contains a period, use this format for setting values on the command line:
        # --set config."http\.enabled"=true
        http.enabled: false
        http.port: 5066
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
