helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## NvidiaGPUBeat ###############################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "nvidiagpubeat"
  namespace: "elk"
  labels:
    chart: "nvidiagpubeat"
    component: "nvidiagpubeat"
    namespace: "elk"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/nvidiagpubeat'
  version: "0.1.0"
  values:
    - replicas: 0

      image:
        repository: "vanvalenlab/nvidiagpubeat"
        tag: "dev"
        pullPolicy: "Always"

      service:
        type: "ClusterIP"

        httpIngressEnabled: true
        internalHttpPort: 8080
        httpTargetPort: 8080
        externalHttpPort: 8080

        httpsIngressEnabled: false

      nodeSelector:
{{ if eq (env "CLOUD_PROVIDER" | default "aws") "aws" }}
        beta.kubernetes.io/instance-type: '{{ env "AWS_GPU_MACHINE_TYPE" | default "p2.xlarge" }}'
{{ else }}
        cloud.google.com/gke-accelerator: '{{ env "PREDICTION_GPU_TYPE" | default "nvidia-tesla-k80" }}'
        cloud.google.com/gke-preemptible: "true"
{{ end }}

      env:
        RPC_PORT: "8500"
        REST_PORT: "8501"
        REST_TIMEOUT: "90000"
        MODEL_PREFIX: "models"
        TF_SERVING_CONFIG_FILE: "/kiosk/nvidiagpubeat/models.conf"
        CLOUD_PROVIDER: '{{ env "CLOUD_PROVIDER" | default "aws" }}'
        LOG_LEVEL: "3"
        DEBUG: "FALSE"
