helmDefaults:
  wait: true
  timeout: 600
  force: true

repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:

################################################################################
## prometheus-adapter                                                         ##
## exports data for the cutom metrics API                                     ##
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/prometheus-adapter
#   - https://github.com/DirectXMan12/k8s-prometheus-adapter
#
- name: prometheus-adapter
  namespace: monitoring
  labels:
    chart: prometheus-adapter
    repo: stable
    component: monitoring
    namespace: monitoring
    vendor: coreos
    default: true
  chart: stable/prometheus-adapter
  version: 2.5.0
  wait: true
  values:
    - logLevel: 4

      metricsRelistInterval: 1m

      # Url to access prometheus
      prometheus:
        url: http://prometheus-operator-prometheus
        port: 9090

      replicas: 1

      resources: {}
        # requests:
        #   cpu: 100m
        #   memory: 128Mi
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
