repositories:
  # Stable repo of official helm charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:

################################################################################
## OpenVPN #####################################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/stable/openvpn/values.yaml
#
- name: openvpn
  namespace: kube-system
  labels:
    chart: openvpn
    component: openvpn
    namespace: kube-system
    vendor: openvpn
    default: true
  chart: stable/openvpn
  version: 4.2.3
  wait: true
  timeout: 600
  atomic: true
  cleanupOnFail: true
