helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## OpenVPN #####################################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/stable/openvpn
#
- name: "openvpn"
  namespace: "deepcell"
  labels:
    chart: "openvpn"
    component: "openvpn"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: 'stable/openvpn'
  version: "1.1.0"
