apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress_name }}
  annotations:
{{- range $name, $value := .Values.ingress.annotations }}
{{- if not ( empty $value) }}
        {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress_path }}
        backend:
          serviceName: {{ .Values.service_name }}
          servicePort: {{ .Values.service_port }}
