# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: integration-tests

on: [push, pull_request]
# on:
#   pull_request:
#     branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        CLOUD_PROVIDER:
          - gke

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        export_default_credentials: true

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Run Integration Tests
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        CLOUDSDK_BUCKET: ${{ secrets.CLOUDSDK_BUCKET }}
        CLOUDSDK_COMPUTE_REGION: us-west-1
        REGION_ZONES_WITH_GPUS: us-west1-a,us-west1-b
        IMAGE: ${{ github.repository }}:${{ github.sha }}
      run: |
        docker buildx build --load --tag ${{ env.IMAGE }} .
        docker run -d -it \
          --env CLOUD_PROVIDER=${{ matrix.CLOUD_PROVIDER }} \
          --env GCP_SERVICE_ACCOUNT=${{ env.GCP_SERVICE_ACCOUNT }} \
          --env CLOUDSDK_CORE_PROJECT=${{ env.CLOUDSDK_CORE_PROJECT }} \
          --env CLOUDSDK_BUCKET=${{ env.CLOUDSDK_BUCKET }} \
          --env CLOUDSDK_COMPUTE_REGION=${{ env.CLOUDSDK_COMPUTE_REGION }} \
          --env REGION_ZONES_WITH_GPUS=${{ env.REGION_ZONES_WITH_GPUS }} \
          --env GOOGLE_APPLICATION_CREDENTIALS=${{ env.GOOGLE_APPLICATION_CREDENTIALS }} \
          --entrypoint=/bin/bash \
          --name kiosk \
          ${{ env.IMAGE }}
        docker exec kiosk make test/integration/${{ matrix.CLOUD_PROVIDER }}/deploy
        docker kill kiosk && docker rm kiosk
