name: Test Kiosk Deployment on GKE 


on:
  push:
    branches:
    - feature/cicd

# Environment variables available to all jobs and steps in this workflow
env:
  CHARTS_PATH: /home/runner/work/kiosk/kiosk/conf/charts
  CLOUD_PROVIDER: gke 
  CLOUDSDK_BUCKET: deepcell-output-benchmarking
  CLOUDSDK_COMPUTE_REGION: us-west1
  CLOUDSDK_CONFIG: /home/runner/work/kiosk/.config/gcloud/
  CLOUDSDK_CORE_PROJECT: deepcell-209717
  CLOUDSDK_CORE_VERBOSITY: debug
  CONSUMER_MACHINE_TYPE: n1-highmem-2
  GCP_PREDICTION_GPU_TYPE: nvidia-tesla-t4
  GCP_TRAINING_GPU_TYPE: nvidia-tesla-v100
  GKE_MACHINE_TYPE: n1-standard-1
  GKE_NODE_SERVICE_ACCOUNT_EMAIL: continuous-integration-test@deepcell-209717.iam.gserviceaccount.com
  GPU_MACHINE_TYPE: n1-highmem-2
  GPU_MAX_DIVIDED_BY_FOUR: 1
  GPU_MAX_DIVIDED_BY_THREE: 1
  GPU_MAX_DIVIDED_BY_TWO: 2
  GPU_MAX_TIMES_FIFTY: 200 
  GPU_MAX_TIMES_FIVE: 20
  GPU_MAX_TIMES_FOUR: 16
  GPU_MAX_TIMES_FOURTY: 160 
  GPU_MAX_TIMES_ONE_HUNDRED: 400 
  GPU_MAX_TIMES_ONE_HUNDRED_FIFTY: 600 
  GPU_MAX_TIMES_SEVENTY_FIVE: 300 
  GPU_MAX_TIMES_TEN: 40
  GPU_MAX_TIMES_THIRTY: 120 
  GPU_MAX_TIMES_THREE: 12
  GPU_MAX_TIMES_TWENTY: 80
  GPU_MAX_TIMES_TWO: 8
  GPU_MAX_TIMES_TWO_HUNDRED: 800 
  GPU_NODE_MIN_SIZE: 0
  GPU_NODE_MAX_SIZE: 4
  GPU_PER_NODE: 1
  REGION_ZONES_WITH_GPUS: us-west1-a,us-west1-b

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout branch
      uses: actions/checkout@v1
    #- name: setup gcloud CLI
      #uses: actions/gcloud/auth@master
      #env:
      #  GCLOUD_AUTH: ${{ secrets.GKE_KEY_BASE64 }}
    - name: decrypt gke service account key
      run: ./.github/workflows/decrypt_gke_service_account_key.sh
      env:
        GKE_KEY_PASSPHRASE: ${{ secrets.GKE_KEY_PASSPHRASE }}
    #-name: write gke service account key to file
    #run: ./.github/workflows/write_gke_service_account_key_to_file.sh
    - name: run cluster setup
      run: make test
